### ISSUE TITLE
Add default options to PackageManager prompts

### ISSUE THREAD

**Issue by samcofer** [sol-eng/wbi#118]
I encountered this during testing, I assumed pypi was a default, but got booted.

![image](https://user-images.githubusercontent.com/47065669/227287958-4624b968-1896-4921-a881-a524f4596239.png)

**Comment by tnederlof** [comment]
Hmm what URL did you input and what repo name did you input?

**Comment by samcofer** [comment]
https://packagemanager.rstudio.com/

**Comment by samcofer** [comment]
I didn't input a repo name. That's why we should have a default suggested repo name, or put out a better error message? Can we set it up to prevent it from booting us out and just allow the user to re-enter the repo name? It feels bad to just get kicked out.
