### ISSUE TITLE
Verify SSL cert/key

### ISSUE THREAD

**Issue by tnederlof** [sol-eng/wbi#5]
We capture SSL certificates and key file paths in the CLI tool but currently do not verify anything about them. Invalid/incomplete certificates and keys are a frequent source of installation errors and support tickets. Being able to automatically check if the cert and key are valid would help identify problems before they cascade down the line.

Perhaps we could use the `openssl verify` command? https://www.openssl.org/docs/man1.1.1/man1/openssl-verify.html

@samcofer you have more knowledge in this space, would be great to get you input!

**Comment by samcofer** [comment]
Hey Trevor, 

Here are a few thoughts in this space. Firstly I would verify that the certificate and key that are presented actually match using these commands:

openssl rsa -noout -modulus -in /path/to/your/private.key  2> /dev/null | openssl md5

openssl x509 -noout -modulus -in /path/to/your/certificate.crt 2> /dev/null | openssl md5

Each of these commands will output an md5 hash that will match if the key and certificate are cryptographically compatible. You can also perform an optional test to verify the validity of the certificate chain they provide with openssl verify as you suggest, but I wouldn't produce an error if this check fails, but print a warning message that says this:
